apiVersion: v1
kind: Service
metadata:
  name: pdcm-admin-ui-service
  namespace: pdx-admin-interface
  labels:
    name: pdcm-admin-ui-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32284
  selector:
    app: pdcm-admin-ui
  type: NodePort
