apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-admin-ui-dev
  namespace: pdx-admin-interface-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdcm-admin-ui-dev
    spec:
      containers:
        - name: pdcm-admin-ui-dev
          image: "pdxfinder/pdcm-admin-ui:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
